[FIX] woqlclient/connectionCapabilities.py
terminusdb/terminusdb-client-python pull request #152
Opened 2020-10-05 13:43 UTC by Darshnadas

Consider iterating the dictionary directly instead of calling .keys(). Using for key in the dictionary would always iterate the dictionary keys.

2020-10-06 21:41 UTC, Cheukting requested changes
I cannot merge it before it has been corrected. Thanks for the effort. I will review it again when it is updated.

2020-10-06 21:41 UTC, Cheukting commented on terminusdb_client/woqlclient/connectionCapabilities.py
> +        for docid in self.dbdocs():
This is not correct... it should be self.dbdocs instead of self.dbdocs() as dbdocs is a dictionary, not a callable.

2020-10-06 21:41 UTC, Cheukting commented on terminusdb_client/woqlclient/connectionCapabilities.py
> +        for docid in self.dbdocs():
Same issue as above

2020-10-07 05:57 UTC, Darshnadas commented on terminusdb_client/woqlclient/connectionCapabilities.py
> +        for docid in self.dbdocs():
@Cheukting Ah! My bad. Updated the PR.

2020-10-07 11:30 UTC, Cheukting approved these changes
Thanks! It looks good!

2020-10-07 11:31 UTC, merged