Fix (#121) - Added type annotations
terminusdb/terminusdb-client-python pull request #153
Opened 2020-10-05 17:38 UTC by KarenImmanuel

Please read https://github.com/terminusdb/terminus-client-python/blob/master/Contributing.md
before submitting a pull request.

Fix for #121 
https://github.com/terminusdb/terminusdb-client-python/issues/121

Added parameter and class anotations for **woql_view.py**.
The types of some parameters were ambigous - so I did not annotate them (example : input_radius, input_size, input_choice, input_obj etc ...)

2020-10-05 18:00 UTC, Cheukting requested changes
I have commented on the types that you are not sure, would you like to add them in?

2020-10-06 15:25 UTC, i-karen commented on terminusdb_client/woqlview/woql_view.py
> +    def collision_radius(self, input_radius) -> WOQLView:
Maybe I can take a generic numeric type for these cases!

2020-10-06 15:45 UTC, i-karen commented
Added the above changes. Please review again!

2020-10-06 21:32 UTC, Cheukting approved these changes
Looks good, thanks!

2020-10-06 21:37 UTC, Cheukting commented
One last thing, since "from __future__ import annotations" is not supported on Python 3.6. I think you can skip it or only import it if the Python version is >= 3.7 (using sys.version)

2020-10-07 14:19 UTC, i-karen commented
Okay, I can add a check there.
However, for less than Python 3.7, the class type annotation should be enclosed in strings as indicated here https://stackoverflow.com/questions/33533148/how-do-i-type-hint-a-method-with-the-type-of-the-enclosing-class

Any suggestions here?

2020-10-08 12:12 UTC, i-karen commented
I added the selective import based on version?

Is there any import guideline from PEP or is this okay?
@Cheukting

2020-10-12 18:31 UTC, Cheukting commented
@i-karen yea I can see the checker is complaining about that. Let me have a look and maybe we can switch that off.

2020-10-12 18:36 UTC, Cheukting requested changes
Almost there, thanks!

2020-10-12 18:36 UTC, Cheukting commented on terminusdb_client/woqlview/woql_view.py
> +    from __future__ import annotations
for now, let's add "# noqa" at the end of this like to by-pass the flaks8 check. See if Travis pass this time.

2020-10-16 16:28 UTC, i-karen commented
Hey @Cheukting , I removed the annotations for class self as it was making things complicated.
Now, all the Travis CI builds pass!

2020-10-19 14:40 UTC, Cheukting commented
@i-karen Cool, nice work! Thank you so much.

2020-10-19 14:40 UTC, merged